# Generated by Django 6.0.3 on 2026-03-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('low_stock_limit', models.IntegerField(default=5)),
            ],
        ),
    ]
